### ISSUE TITLE
Minigames remain active

### ISSUE THREAD

**Issue by ThatsLiamS** [Coin-Flipper/Coin-Flipper#3]
If an error occurs during a minigame, it will remain active within the guild preventing other minigames from starting forever. From what I can tell, approximately 10 guilds are affected by this, as we have since patched the minigames so it doesn't cause any issues.

![image](https://user-images.githubusercontent.com/73022526/127735924-f3ada6d9-0210-48d2-8b2b-0ab2b59cad70.png)

## **Potential solution:** 

Create a `c!resetserver` command, this will set the minigame status to false and all customization settings to the default _(So this would correct any potential issues with the customization aswell)_

**Comment by AsyncBanana** [comment]
Another potential solution would be to store a timestamp of the last minigame and make an override if the minigame is more than x old (probably 1 or 2 minutes to give all minigames more than enough time to finish). Alternatively, the data could also include the max time that minigame could take if you want per minigame timing precision. This minimizes the time between a minigame erroring and being able to play another, but it would be more complex and take slightly more space.
However, I think making a `c!resetserver` command is still a good idea to allow for data migration and any other errors involving data storage, as you said.

**Comment by ThatsLiamS** [comment]
The issue still occurs for the guilds that were affected, the feature to correct this will be released in the `2.0.0` update as part of the customization commands.
